#!/usr/bin/env bash

# Quick Reference - E2E Test Commands

echo "AI Image Generator - Test Commands Quick Reference"
echo ""
echo "QUICK START:"
echo "  npm run server                          # Start API server"
echo "  npm run test:e2e:api                   # Run API end-to-end tests"
echo "  npm run test:integration               # Run integration tests"
echo "  npm run test:e2e:frontend              # Run frontend tests (headless)"
echo ""
echo "ALL TESTS:"
echo "  npm run test                           # Run all unit tests"
echo "  npm run test:watch                     # Run tests in watch mode"
echo "  npm run test:coverage                  # Run with coverage report"
echo "  npm run test:all                       # Run E2E + Integration + Frontend"
echo "  npm run test:ci                        # CI/CD optimized test run"
echo ""
echo "FRONTEND SPECIFIC:"
echo "  npm run test:e2e:frontend:headed       # Run with browser visible"
echo "  npm run test:e2e:frontend:debug        # Run with Playwright inspector"
echo ""
echo "TEST FILES:"
echo "  tests/e2e/system.test.ts               # Complete API workflows (36+ tests)"
echo "  tests/e2e/frontend.test.ts             # Browser UI tests (40+ tests)"
echo "  tests/integration/api.test.ts          # API endpoints (25+ tests)"
echo ""
echo "DOCUMENTATION:"
echo "  TESTING.md                             # Full testing guide"
echo "  TEST_SUITE.md                          # Test coverage details"
echo ""
echo "SETUP VERIFICATION:"
echo "  ./tests/verify-setup.sh                # Check test environment"
echo "  ./tests/run-tests.sh                   # Full Docker-based test run"
echo ""
echo "ENVIRONMENT:"
echo "  Create .env.test with:"
echo "    API_URL=http://localhost:5000/api"
echo "    FRONTEND_URL=http://localhost:5173"
echo "    DATABASE_URL=file:./test.db"
echo "    NODE_ENV=test"
echo ""
